//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanXang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CATRUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATRUC()
        {
            this.CHITIETNGAYLAMs = new HashSet<CHITIETNGAYLAM>();
        }
    
        public int MaCaTruc { get; set; }
        [DisplayName("Tên ca trực")]
        public string TenCaTruc { get; set; }
        [DisplayName("Giờ bắt đầu")]
        public Nullable<System.TimeSpan> GioBatDau { get; set; }
        [DisplayName("Giờ kết thúc")]
        public Nullable<System.TimeSpan> GioKetThuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNGAYLAM> CHITIETNGAYLAMs { get; set; }
    }
}
