//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanXang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CHITIETNGAYLAM
    {
        public int MaCaTruc { get; set; }
        [DisplayName("Tên nhân viên")]
        public int MaNV { get; set; }
        [DisplayName("Ngày làm")]
        public System.DateTime NgayLam { get; set; }
        [DisplayName("Chỉ số đầu")]
        public Nullable<double> ChiSoDau { get; set; }
        [DisplayName("Chỉ số cuối")]
        public Nullable<double> ChiSoCuoi { get; set; }
        [DisplayName("Cột bơm")]
        public Nullable<int> MaCot { get; set; }
        public int MaCTNL { get; set; }
    
        public virtual CATRUC CATRUC { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual COTBOMXANG COTBOMXANG { get; set; }
    }
}
