//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanXang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CTPHIEUBAN
    {
        public int MaCTPB { get; set; }
        public Nullable<int> MaPB { get; set; }
        [DisplayName("tên hàng hóa")]
        public Nullable<int> MaHH { get; set; }
        [DisplayName("Số lượng")]
        public Nullable<int> SoLuong { get; set; }
        [DisplayName("Đơn giá")]
        public Nullable<decimal> DonGia { get; set; }
        [DisplayName("Quy cách")]
        public Nullable<int> MaQC { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual PHIEUBAN PHIEUBAN { get; set; }
        public virtual QUYCACH QUYCACH { get; set; }
    }
}
