//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanXang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LUONG
    {
        public int IDluong { get; set; }
        [DisplayName("Tên nhân viên")]
        public Nullable<int> MaNV { get; set; }
        [DisplayName("Số ca tối")]
        public Nullable<int> SoCaToi { get; set; }
        [DisplayName("Số ca sáng")]
        public Nullable<int> SoCaSang { get; set; }
        [DisplayName("Tổng phụ cấp")]
        public Nullable<decimal> TongPC { get; set; }
        [DisplayName("Tổng lương theo ca")]
        public Nullable<decimal> TongLuongTheoCa { get; set; }
        [DisplayName("Ngày tính")]
        public Nullable<System.DateTime> NgayTinh { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
