//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanXang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUCAP
    {
        public int MaPC { get; set; }
        public string TenPC { get; set; }
        public Nullable<decimal> SoTien { get; set; }
    }
}
