//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanXang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLY
    {
        public int MaQL { get; set; }
        public string TenQL { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgSinh { get; set; }
        public string DiaChi { get; set; }
        public string Sdt { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
